#!/usr/bin/env bash
# Write android/local.properties from the SDK this machine actually has.
#
# WHY THIS EXISTS: `local.properties` is gitignored — correctly, it is a
# per-machine path — but nothing generated it. It was written by hand once, and
# that has two consequences that only show up later.
#
# **A worktree has no `local.properties` at all.** This repo's own norm is that
# multi-turn work happens in `worktrees/croft/<slug>` (CLAUDE.md § Concurrent
# sessions), and gradle resolves the file relative to the project directory, so
# every worktree gets `SDK location not found` from `make gate` — a green gate
# in one checkout and a red one in another, for a reason that has nothing to do
# with the code. Found by running `make gate` in a P7 S0 worktree.
#
# **The hand-written one pointed at the stub.** It said
# `sdk.dir=$HOME/Library/Android/sdk`, which on this machine holds
# platform-tools and nothing else; the real SDK is the Homebrew cask at
# /opt/homebrew/share/android-commandlinetools. That is the same wrong default
# that broke `make emulator` (ops/JOURNAL.md, 2026-08-26) — the third place the
# Android-Studio path was assumed. So this uses `verify.sh`'s candidate probe
# verbatim rather than inventing a fourth answer.
#
# Idempotent and safe to re-run: it rewrites the file every time, because the
# right value is whatever the probe says today.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/.." && pwd)"

# verify.sh's rule, unchanged. The `cmdline-tools` marker is what distinguishes
# a real SDK from the stub — a bare directory check is not enough.
sdk="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-}}"
if [ -z "$sdk" ]; then
  for cand in "$HOME/Library/Android/sdk" "/opt/homebrew/share/android-commandlinetools"; do
    [ -d "$cand/cmdline-tools" ] && { sdk="$cand"; break; }
  done
  sdk="${sdk:-$HOME/Library/Android/sdk}"
fi

if [ ! -d "$sdk" ]; then
  echo "Android SDK not found at $sdk — run 'make bootstrap', or set ANDROID_SDK_ROOT" >&2
  exit 1
fi

out="$root/android/local.properties"
printf '# Generated by env/android-local-properties.sh. Per-machine, gitignored.\n' > "$out"
printf '# Re-run that script rather than editing this by hand — a hand-edited copy\n' >> "$out"
printf '# is how this file came to point at a stub SDK for two months.\n' >> "$out"
printf 'sdk.dir=%s\n' "$sdk" >> "$out"
echo "==> $out -> $sdk"
